Update k8setup.yaml

diff --git a/.github/workflows/k8setup.yaml b/.github/workflows/k8setup.yaml
--- a/.github/workflows/k8setup.yaml
+++ b/.github/workflows/k8setup.yaml
@@ -15,7 +15,6 @@ jobs:
 
       - name: Install Docker
         run: |
-          # Installing Docker
           sudo apt update
           sudo apt -y install docker.io
           sudo systemctl start docker
@@ -24,10 +23,13 @@ jobs:
 
       - name: Install Kubernetes and fix GPG key
         run: |
-          # Fix GPG key for Kubernetes repository
+          # Remove old GPG key if it exists
+          sudo apt-key del 234654DA9A296436 || true
+          
+          # Add the new GPG key for Kubernetes
           curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
           
-          # Add Kubernetes repository
+          # Add the Kubernetes repository
           sudo apt-add-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main"
           
           # Update package list
@@ -64,7 +66,15 @@ jobs:
           # Construct the URL to download kubectl and ensure it's correct
           URL="https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
           echo "Download URL: $URL"
-          curl -LO "$URL"
+          
+          # Fetch and check if the URL is valid
+          curl -O "$URL"
+          
+          # Check if the file was downloaded correctly
+          if [ ! -f "./kubectl" ]; then
+            echo "Failed to download kubectl."
+            exit 1
+          fi
 
       - name: Install kubectl
         run: |
